API_ID: 16704309
API_HASH: e42828860d91fb36ed95d9b273a3ce77
BOT_TOKEN: 5410031112:AAEKSKS-j4F63-R0fCSTCWhenmKi9TmOE8c


MONGO_URL: mongodb://mongo:m8Z5ncOh5pbAVsaKoLsm@containers-us-west-79.railway.app:6763
REDIS_URI: redis-12318.c241.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT: 12318
REDIS_PASS: KHXvWWZwVliC8GM0SGTaxnxwQsy2n9dd

SESSION_API_ID: 16704309
SESSION_API_HASH: e42828860d91fb36ed95d9b273a3ce77
SESSION_STRING: 1BVtsOGkBuzuPpR1Fv67kDMVxhnbdkyqmphuAvyGQBUsVH7Qi209f5MpkCWSP0Xz_Q3lG_U42kBCMfxkFM07StkDGBVcwYs3DfdZXANzdSrPVN7z_jSByXCIYRlPW8xc1jNg7PyR750N1q-p2NihkB4y5jVfwkIhFI8X7kVSIZjKle04dNF5ekW9c0IY894MbnD1uoxB---H2croPKPpKKBh23Qjgv4qfP8BPSfmtN-FZN-iCYCURI09tO9lQhKZE9YQ0zh2tiUf8yDqTioxWZXFh51k39DgPgJbP53XxiakoW1yLNkoAnXwagHe9i6PmkQcq4ucfDr1cGUOjhS37xPqABWYtM_M=

ADMINS: 
  - 5433600338
  - 2091328202

OWNER: 
  - 5433600338

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: Carders36 
# LOG_CHAT: 
LOG_CHAT: -1001856906497



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

